apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: customers
  labels:
    strimzi.io/cluster: edh
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 604800000
    cleanup.policy: compact
    delete.retention.ms: 100
    segment.ms: 100
    min.cleanable.dirty.ratio: 0.01