apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter-service
  namespace: ingestion
spec:
  selector:
    app.kubernetes.io/name: "kafka-exporter"
  ports:
    - protocol: TCP
      port: 9404
      targetPort: 9404