apiVersion: "kafka.strimzi.io/v1beta2"
kind: "KafkaConnector"
metadata:
  # connector name
  name: "sink-yugabytedb-ysql-postgres-coffee-json-493488f0"
  labels:
    # kafka connect [cluster] name
    strimzi.io/cluster: edh
spec:
  class: io.confluent.connect.jdbc.JdbcSinkConnector
  tasksMax: 2
  config:
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: true
    value.converter.schemas.enable: true
    connection.url: "jdbc:postgresql://yb-tservers.database.svc.cluster.local:5433/owshq?user=yugabyte&password=yugabyte"
    connection.attempts: "2"
    topics: "src-postgres-coffee-json"
    table.name.format: "postgres_coffee"
    auto.create: "true"
    auto.evolve: "true"
    insert.mode: "upsert"
    pk.mode: "record_key"
    pk.fields: "incr"
    batch.size: "1500"
    delete.enabled: true
